# Generated by Django 3.0.5 on 2020-05-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200524_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datacompleted',
            new_name='datecompleted',
        ),
    ]
